### PR TITLE
Make about/ontologies page

### PR DESCRIPTION
**Pull request by justaddcoffee**
Made separate ontology page

### CODE REVIEW

**Comment by nlharris** [comment]
This seems reasonable to me. @monicacecilia may have suggestions about improving the wording. (I wonder, for example, if "maintains" is too weak a word--Monarch has created most of those ontologies!)

It doesn't look like this PR provides a way to add publications to the ontologies, as discussed in #273 -- should we make a new issue for that?

**Comment by justaddcoffee** [comment]
@nlharris @monicacecilia Nico please reword as you see fit - s/maintain/developed and maintains/ or whatever

We can add publications (and lots of other things) programmatically - basically anything in this YAML is dead easy to add: 

https://github.com/monarch-initiative/monarch-ui/blob/master/public/ontologies.yml

**Comment by matentzn** [comment]
Is this yaml kept in sync with the obofoundry yaml? why not just link to obofoundry directly?

**Comment by justaddcoffee** [comment]
> Is this yaml kept in sync with the obofoundry yaml? why not just link to obofoundry directly?

I originally was pulling this from obofoundry, but refactored b/c they don't use `https`, so Vue.js doesn't like this

**Comment by matentzn** [comment]
> I originally was pulling this from obofoundry, but refactored b/c they don't use https, so Vue.js doesn't like this

Just make sure the yaml stays in sync.. There should be a routine refreshing it every now and then.. This yaml file is changing a lot!

**Comment by monicacecilia** [comment]
Closing, with #295 and #273, as agreed during Monarch-UI check-in on 2020-03-02. 
We are keeping this page as is https://beta.monarchinitiative.org/about/licensing - and adding a link from sub menu for 'Ontologies' from the 'About' top-level menu item. See #296

**Pull request closed without merging**
