### PR TITLE
Setup prettier, format, relint, fix errors

### PR DESCRIPTION
**Pull request by vincerubinetti**
First of many steps to attempt to clean the code base up. Having the simplest possible eslint/formatting configuration will help maintain better code quality and consistency.

@kevinschaper I was able to test and verify every line of code I modified (comparing it to the current live site to make sure it still worked), EXCEPT FOR the TaxonFilter component, which is apparently supposed to appear above the AssocTable here:

image

There are some flags to supposedly make it appear, but I couldn't get it to appear naturally, so I don't know what the intended behavior is. Can you point me to a node or setting where that component will appear so I can test it. The component was improperly mutating `props`, which you're not supposed to do and will have no effect (I wouldn't be surprised if it wasn't working because of this).

- reset eslint rules to default and recommend rules, no custom rules
- fix eslint errors that arise, several deprecated methodologies
- reformat with default prettier config

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Note, build is failing due to a case-sensitive error [like this](https://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git). I renamed `Entrez` to `entrez` (and etc.) without using the `git mv` command, so they still appear uppercase on GitHub, leading to the issues.

**Comment by kevinschaper** [comment]
I don't know anything about the TaxonFilter component, @monicacecilia @jmcmurry do you know any node pages that it would naturally appear on?

**Review by kevinschaper — APPROVED** [review]

**Review by kshefchek — APPROVED** [review]

**Comment by jmcmurry** [comment]
To answer your question @kevinschaper, species filters are mostly useful on ortholog phenotypes on gene node pages. In theory, we will have more animal diseases in the system some day (eg. from OMIA, Canine databases). However, right now there's no explicit flag for species in our disease model right now. So things like bovine Marfan are just floating out there without a way to filter.

**Comment by vincerubinetti** [comment]
So the taxon filter sounds like it's essentially "dead code" in the sense that it was perhaps a planned feature that never got implemented or tested? If that's the case, let's just merge without testing that particular feature and deal with problems when/if that feature ever gets implemented. I'm fairly sure I refactored correctly such that I fixed the eslint error but didn't change the behavior of the existing code.

**Comment by kshefchek** [comment]
We want the taxon filter to be functional, you can see it on gene pages on the homolog and ortholog-x tabs, eg https://monarchinitiative.org/gene/HGNC:3603#homolog

**Comment by vincerubinetti** [comment]
Thanks @kshefchek that was the info I was looking for. Instead of trying to fix the eslint errors in taxon map now, I'm just going to put in ignores. The component seems to mutate props, which you're not supposed to do (and isn't even supposed to work). Truly fixing it would require much more study and rewriting the way the component and its parent works. The way it works right now seems very hacky and improper.

**Pull request merged**
