### PR TITLE
fixes for #301, #282, other updates

### LINKED ISSUE #282: Do not show frequency and onset for inferred disease to phenotype associations
I am not sure if it is a good idea to display phenotype associations for "middle nodes" in Mondo. 
In any case, it is incorrect to inherit the frequencies "up" the hierarchy.

For instance,
amino acid or protein metabolism disease with epilepsy
https://beta.monarchinitiative.org/disease/MONDO:0016399#phenotype

is noted to have as obligate:
branched-chain keto acid dehydrogenase kinase deficiency | Obligate |  

but the "Obligate" is coming from one of the descendents and does not apply to the entire group.

### LINKED ISSUE #301: Fix broken links from Monarch 'Model' tab to model pages in FlyBase
All the links from items listed in the 'Model' tabs in Monarch, that are pointing to FlyBase pages, are broken. 

For example, links to _D. melanogaster_ models associated with [this disease](https://beta.monarchinitiative.org/disease/MONDO:0007113#model), and this [publication](https://beta.monarchinitiative.org/publication/PMID:18701717#model), lead to warning pages stating "_No such path available: /sequence featurevariant/FlyBase:FBal#######_," like [this one](https://beta.monarchinitiative.org/sequence%20featurevariant/FlyBase:FBal0244600).

### PR DESCRIPTION
**Pull request by kshefchek**
- Fixes #301

- Fixes #282

- Partially addresses #283, the rest will need to come from BioLink, this is pretty trivial but we should wait until we're ready to merge this PR to not break beta

- Implemented https://github.com/monarch-initiative/monarch-ui/issues/108#issuecomment-595835777, would be good for those familiar with genotype nomeclature to review - @mbrush and @justaddcoffee

- For phenotype profile search, updates the autocomplete filters so that only genes and diseases associated with phenotypes will show up, after selecting a gene or disease, associated phenotypes are limited to direct associations (to avoid duplicated phenotypes, confusing results), filter out gene-EFO associations

- Fix disease and phenotype data pages for terms that are not in our scigraph ontology instance (OMIA, some EFO)

- Fixes ajax loader for tables

- Small bits of linting cleanup but lots more to go, reverted airbnb to 13.2 to since v14 contains ES2018 rules that I'm not sure we need to consider just yet

staged on https://monarch-initiative.github.io/monarch-ui because i accidentally did this on a branch not a fork

### CODE REVIEW

**Comment by kshefchek** [comment]
i've also added travis to run our unit tests and eslint, eslint is failing (the majority not from this PR).  I propose we not let us block anything and clean up the code post release

**Comment by monicacecilia** [comment]
@kshefchek, have you and @iimpulse already coordinated how to reconcile your branches? 
Is this PR ready for review?

**Comment by kshefchek** [comment]
I merged a portion of @iimpulse's branch here to resolve the AnalyzePhenotype.vue conflicts, I was hoping that branch would get merged in first before this one so I can do some final linting and cleanup, as well as replace noncausal with correlated

**Comment by iimpulse** [comment]
:shipit:

**Comment by kshefchek** [comment]
we could add an eslint rule to disallow console.logs - https://eslint.org/docs/rules/no-console

**Pull request merged**
