### PR TITLE
fix causal gene evidence fetch

### LINKED ISSUE #457: Evidence tables broken - displaying endless ajax spinner
Evidence tables (eg https://beta.monarchinitiative.org/disease/MONDO:0007947#causal-gene -> click support button) are currently endlessly spinning.

They appear to be working in the deploy preview for  https://github.com/monarch-initiative/monarch-ui/pull/448, so I wonder if it's related to the formatting PR (this is my fault I thought I manually tested it).

### PR DESCRIPTION
**Pull request by vincerubinetti**
Closes #457

### CODE REVIEW

**Review by kshefchek — APPROVED** [review]
looks good! do we know why prettier or format made this change?

**Comment by vincerubinetti** [comment]
I made this change because of eslint. You're not supposed to mutate `props` being passed down to a component, but this is what this component was doing. So I essentially had made `that` into a deep copy of `this` instead of a copy by reference so we weren't mutating props. But it turns out that was necessary for the "evidence cache" or something. In this pr I reverted that change and simply had eslint ignore the props mutation.

**Comment by kshefchek** [comment]
makes sense! I wrote this component so I would be curious if there's a better way.  I added the cache in because sometimes these calls result in a large call to our API, so in hopes of reducing the burden on both the client and our API (maybe I should be using local storage here instead).

**Comment by vincerubinetti** [comment]
Generally speaking you're supposed to emit events to parent components to update state. The general rule of thumb is props down, events up. In fact, I don't think mutating props is even supposed to work in Vue. It doesn't in React either. But I'm guessing it works in this case because the prop is an object, and you're changing a nested prop in it rather than the object itself. 

Regarding cache, it's probably better to do that near the api code itself, ie in `/api`, not in the component. There are ways to set up api code such that you can cache responses from any api call/end point (if you want to), cancel concurrent requests, etc. 

localStorage probably isn't desired either. Imo when the user does a hard refresh of the app/page, they should be sure they're getting up-to-date info from the API. I usually only cache things on a "per session" basis. You could do that with sessionStorage, but then you'd have to convert everything to strings which is error prone, and sessionStorage is limited to ~5 mb. Thus caching things simply in memory (variables) is probably the way to go.

**Pull request merged**
