### PR TITLE
0.0.7 - AnalyzePhenotypes fixes. ESLint changes. Code cleanup. Faster page load. Error handling.

### PR DESCRIPTION
**Pull request by DoctorBud**
0.0.7
- Add another e2e test.
- Use BL 'development' which has the new shiny singular get_association_counts, as well as some other fixes.
- REALLY parallelize the BL calls to /graph and /bioentity. 0.0.6   prepped for this.
- Simplify Node.vue by eliminating the progress timer, which appears to   have been obviated over time.
- Eliminate the unnecessary has_gene_track state var in Node.vue.
- Simplify getNodeSummary, which doesn't need uri for LocalNav.vue (although really, all /bioentity funcs should return uri if possible.
- Calling the /identifier/prefixes/expand endpoint is stupid).
- Fixes many bugs in AnalyzePhenotypes.vue and LocalNav.vue.
- Improves layout of AP slightly
- Improves example used for debugging
- Fix some ESLint errors
- Change default for 'npm run lint' to '--nofix'
- Add an 'npm run lintfix' that uses '--fix'

### CODE REVIEW

**Comment by nathandunn** [comment]
Looks good.   +1 

I tested and was fine (good on the parallel calls). 

As a side-note, I'm getting some mass recursion here. 

http://localhost:8082/analyze/phenotypes

**Comment by DoctorBud** [comment]
Thanks @nathandunn ... I'm actually working on the recursion/loop problem right now. Hoping to have a quick fix and amend this PR with it before I merge it. Stay tuned.

**Comment by DoctorBud** [comment]
@nathandunn ... It turns out that AnalyzePhenotypes.vue is broken in many ways, and that LocalNav.vue doesn't really work right unless there is exactly one superclass, equivclass, subclass for a term. It *appears* to work, but its lying and putting the terms in the wrong columns. I'm halfway throughrewriting it now and will amend this PR with the changes, because I think that is faster than trying to extricate my AP changes at this point.

**Comment by nathandunn** [comment]
I thought it was easier if the two jenga blocks are right next to each other

**Comment by nathandunn** [comment]
@DoctorBud  Here is what I found:

- analyze phenotypes works (:+1)
  - you need a way to clear all of the genes and phenotypes in a list
- both lookups now no longer works (I get this error, but with no network submission)

```
nodeResponse ERROR TypeError: Cannot read property 'length' of null
    at _callee5$ (BioLink.js?a74f:272)
    at tryCatch (runtime.js?96cf:62)
    at Generator.invoke [as _invoke] (runtime.js?96cf:288)
    at Generator.prototype.(:8081/anonymous function) [as next] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (BioLink.js:19)
    at _next (BioLink.js:21)
    at eval (BioLink.js:21)
    at new Promise (<anonymous>)
    at Module.eval (BioLink.js:21)
    at Module.getSearchTermSuggestions (BioLink.js?a74f:264) VueComponent {_uid: 28, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: VueComponent, …}
```

screen shot 2019-03-04 at 7 48 37 am

- search API does not always work <http://localhost:8081/search/Shh>:


```
Search ERROR TypeError: Cannot read property '0' of undefined
    at eval (Search.vue?9924:134)
    at Array.forEach (<anonymous>)
    at VueComponent._callee$ (Search.vue?9924:131)
    at tryCatch (runtime.js?96cf:62)
    at Generator.invoke [as _invoke] (runtime.js?96cf:288)
    at Generator.prototype.(anonymous function) [as next] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/Search.vue?vue&type=script&lang=js&:7)
    at _next (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/Search.vue?vue&type=script&lang=js&:9) VueComponent {_uid: 26, _isVue: true, $options: {…}, _renderProxy: Proxy, _self: VueComponent, …}
```
screen shot 2019-03-04 at 7 58 42 am

**Comment by nathandunn** [comment]
👍  Seems to be working.  

I would still add an issue for clearing the list of genes and phenotypes (though you can also reload), so maybe that is lower priority.  

Also, if there is any way to speed up the phenogrid results.  It seems to take a long time on even smaller data sets.  Again, separate issue, and perhaps lower priority.

**Comment by kshefchek** [comment]
@nathandunn I think we can speed up the phenogrid results from biolink.  Currently the biolink call assumes mixed types (diseases, genes, etc) and goes through some extra steps to determine types and find associated phenotypes.  I can work on streamlining the service in the cases where we're only sending phenotypes.

**Pull request merged**
