### PR TITLE
Accordionize data sources

### PR DESCRIPTION
**Pull request by justaddcoffee**
Per @jmcmurry's request for accordionized data source page, this is a little better I think: 
https://justaddcoffee.github.io/monarch-ui/about/data-sources
Missing logo images, but you get the idea

### CODE REVIEW

**Comment by jmcmurry** [comment]
great; looks like the logos don't come through though?

image

**Comment by justaddcoffee** [comment]
> great; looks like the logos don't come through though?

Yep, this is on my personal fork at justaddcoffee.github.io, logo images not loading, but it looks like this: 

Screen Shot 2020-01-30 at 12 38 50 PM

> If possible, it would be great if the logos could be left most and the title text were to the right of it

hang on, I'll give this a try

**Comment by jmcmurry** [comment]
I forgot the logos have differing widths; thinking ...

**Comment by justaddcoffee** [comment]
Looks not terrible, but maybe not better:

Screen Shot 2020-01-30 at 4 25 45 PM

**Comment by jmcmurry** [comment]
Let's just leave the logos only show up after expansion, that way they wont hog vertical space

**Comment by justaddcoffee** [comment]
Done here - does this look okay (unexpanded, expanded):

Screen Shot 2020-01-30 at 4 29 22 PM


Screen Shot 2020-01-30 at 4 29 30 PM

**Comment by jmcmurry** [comment]
beautiful; ship it thanks

**Comment by justaddcoffee** [comment]
Great, thanks @jmcmurry! Can you bless this with a review/approval? Then I'll merge

**Comment by justaddcoffee** [comment]
+1!

**Comment by pnrobinson** [comment]
yes this looks nice!

**Pull request merged**
