### PR TITLE
Support Markdown as VueJS components. Update README. Remove non-working menu items. Adds About Team/Monarch pages.

### PR DESCRIPTION
**Pull request by DoctorBud**
- Adds support for vue-markdown-loader (VML)
- Decompose Home.vue into several VML components.
- Massively simplify the HTML/CSS of the Home Page
- Adds AboutMonarch.md.
- Adds AboutTeam.md page.
- Moves some image assets into public/
- Remove items from Navbar that do not function.
- Add partners/collaborators images to public. Remove experimental and unused markdown loaders.
- Update README.md with NodeJS install instructions

### CODE REVIEW

**Comment by DoctorBud** [comment]
> is this WIP or ready for review?

Ready for review. Works better than before. Not perfect, but buildable upon.

**Comment by nathandunn** [comment]
@DoctorBud  It is working now.  

I would do a .gitignore on everything in the docs directory unless it needs to be in git to make work with github pages

**Comment by DoctorBud** [comment]
Re the docs/ directory... It is currently being pushed with master so that we get convenient GHPages access. In hindsight, I think we should have a separate repo for the *draft* publications, or at least use gh-pages branch. I'd build a `npm run deploy` script that handled this (I have a note to this effect in the README),

So... If I had my way, I'd get this repo to a certain level of functionality, and then destroy and rebuild it. There should be no significant Issues that can't be recreated. So that's my *plan*... Separate building/testing from deployment; kill this repo with all its docs/ wasted space.

**Comment by DoctorBud** [comment]
We are not alone in this issue. It is solved. I have not prioritized it. But there is this https://stackoverflow.com/questions/48588908/deploying-ignored-dist-folder-to-github-pages, and there are many other examples of writing such a script. We still need to decide on a proper way to deploy the static site. GH Pages is nice and free, but I expect we want to host it on our own nginx site with appropriate certificates and monitoring and such. So the GH Pages thing should be treated as a convenience to allow folks to demo their prototype before it is finally committed to master.

**Comment by DoctorBud** [comment]
Basically, I made a mistake in first committing the docs/ directory. I think we should have per-user gh-pages for our forked devs, and an appropriate `npm run publish` script. I think that after we've figured that out, we should nuke this repo and start over. If we only put useful tickets into this repo, then manually transferring them (if they are still useful) is possible: https://help.github.com/articles/transferring-an-issue-to-another-repository/

**Comment by nathandunn** [comment]
@DoctorBud  That's a pretty sweet solution.  FYI @kltm  I think we could use something like this for some of the other docs we work with.

**Pull request merged**
