### PR TITLE
Fixing some css, bigger nav-bar slightly, slight adjustments all around

### PR DESCRIPTION
**Pull request by iimpulse**
- Increasing nav bar height slightly, spacing dropdown items, removing readme & contributing nav-items
- cleaning up footer selection + icons formatting
- Formatting files with attribute breaks to enhance readability. 
- Modifying main content drawer padding
- Supporting static pages should have h2 and centered titles.

These are minor edits as far as I see.

#114

### CODE REVIEW

**Comment by kshefchek** [comment]
On the multiline attributes, this is a recommendation from Vue and Tim and Dan agreed it was a good thing (for diffs, readability? I can't recall).  But if you find the more traditional layout it's just as well.  If we go this route, could you update the eslintrc accordingly?

https://vuejs.org/v2/style-guide/#Multi-attribute-elements-strongly-recommended

**Comment by iimpulse** [comment]
Didn't catch this in the docs. Its tough cause I'm so use to the traditional style. It makes it almost impossible to see the hierarchy. 

It looks like I can still write the code how I want it and lint it after with 

node_modules/.bin/vue-cli-service lint --fix

@pnrobinson Lets follow the style guide and just post lint

**Comment by iimpulse** [comment]
> I definitely agree that we should change items such as
> 
> ```
> <div
>       class="content-wrapper">
> ```
> 
> to
> 
> ```
> <div class="content-wrapper">
> ```
> 
> This makes the code much easier to grok!
> 
> I do not understand the changes to router.js -- several items were deleted, but they did not appear to be replaced anywhere else? Where these items redundant?

These items were deleted because it is not relevant to have the contributing docs or the readme displayed in the web application themselves. I will add a comment to the contact us, or similar pages on contributing to the web application.

**Comment by pnrobinson** [comment]
The Vue rules s*ck, sorry! I admit it is all what you are used to, but I am definitely used to the style that they call bad....

**Comment by kshefchek** [comment]
I don't feel strongly about it, perhaps we could set a rule that anything >3 should be split into multiple lines, 

    {
      "vue/max-attributes-per-line": ["error", {
        "singleline": 3,
        "multiline": {
          "max": 1,
          "allowFirstLine": false
        }
      }]
    }

https://eslint.vuejs.org/rules/max-attributes-per-line.html

**Pull request merged**
