### PR TITLE
Update logos for source databases used in ingests

### PR DESCRIPTION
**Pull request by justaddcoffee**
to address #183 

I've updated many of the logos, and also added some logos for things we can and have previously ingested, but aren't now.

### CODE REVIEW

**Comment by justaddcoffee** [comment]
@monicacecilia @iimpulse

**Comment by justaddcoffee** [comment]
> is there a smaller version of the go icon? 400 kb is on the larger side

Do we really want small here? I think we are going to use these as inline images to populate the new sources page right, analogous to [here](https://monarchinitiative.org/about/sources)...

**Comment by kshefchek** [comment]
I'm considering their usage in our tables: https://github.com/monarch-initiative/monarch-ui/blob/a47591fff220369ca918428528aff2f915d16c8d/src/components/AssocTable.vue#L546 but perhaps we could have small and large versions of the icons?

**Comment by justaddcoffee** [comment]
> I'm considering their usage in our tables:
> 
> https://github.com/monarch-initiative/monarch-ui/blob/a47591fff220369ca918428528aff2f915d16c8d/src/components/AssocTable.vue#L546
> 
> but perhaps we could have small and large versions of the icons?

Okay, didn't realize you were using these there. Maybe small and large versions of each is a good solution. 

What size would you like for the tables? (i.e. 32x32 px, 64x64 px)

**Comment by monicacecilia** [comment]
> I'm considering their usage in our tables:
> but perhaps we could have small and large versions of the icons?

eek. This may have been my oversight. I was only thinking of the ones in the 'sources' pages. Thanks for pointing this out, @kshefchek 

Thanks for working on this, @justaddcoffee!

:bowtie:

**Comment by monicacecilia** [comment]
> What size would you like for the tables? (i.e. 32x32 px, 64x64 px)

How about making the small versions 80 x 80 px -ish? (some are rectangular).

**Comment by monicacecilia** [comment]
Dear @justaddcoffee, are we waiting on other changes? 
Dear @kshefchek, have you had a chance to look into this PR?

ping!

**Comment by justaddcoffee** [comment]
@monicacecilia thanks for the ping. 

We perhaps don't need small and large versions of these after all. Most now are very roughly a few hundred pixels by a few hundred pixels, although this varies, see below. 

Do these sizes below work for everyone? 
@iimpulse @kshefchek @monicacecilia 

Note that I've also converted all logos to PNG for consistency (some were JPG and ICO previously). 

```
~/WebstormProjects/monarch-ui/public/img/sources *update_logos $ file source-* 
source-animalqtldb.png:  GIF image data, version 89a, 243 x 50
source-bgee.png:         PNG image data, 248 x 100, 8-bit colormap, non-interlaced
source-biogrid.png:      PNG image data, 320 x 146, 8-bit/color RGB, non-interlaced
source-clinvar.png:      PNG image data, 398 x 140, 8-bit colormap, non-interlaced
source-coriell.png:      PNG image data, 300 x 94, 8-bit/color RGBA, non-interlaced
source-ctd.png:          PNG image data, 90 x 42, 8-bit/color RGBA, non-interlaced
source-decipher.png:     PNG image data, 203 x 54, 8-bit/color RGBA, non-interlaced
source-ebigene2phen.png: PNG image data, 483 x 482, 8-bit/color RGBA, non-interlaced
source-ensembl.png:      PNG image data, 86 x 81, 8-bit/color RGBA, non-interlaced
source-eom.png:          PNG image data, 725 x 97, 16-bit gray+alpha, non-interlaced
source-flybase.png:      PNG image data, 294 x 72, 8-bit/color RGBA, non-interlaced
source-geneontology.png: PNG image data, 750 x 193, 8-bit/color RGBA, non-interlaced
source-genereviews.png:  PNG image data, 160 x 200, 8-bit/color RGBA, non-interlaced
source-gwascatalog.png:  PNG image data, 178 x 178, 8-bit/color RGBA, non-interlaced
source-hgnc.png:         PNG image data, 196 x 82, 16-bit gray+alpha, non-interlaced
source-hpo.png:          PNG image data, 350 x 135, 8-bit/color RGB, non-interlaced
source-impc.png:         PNG image data, 204 x 146, 8-bit/color RGBA, non-interlaced
source-kegg.png:         PNG image data, 128 x 92, 8-bit colormap, non-interlaced
source-mgi.png:          PNG image data, 115 x 61, 8-bit/color RGB, non-interlaced
source-mmrrc.png:        PNG image data, 300 x 92, 8-bit/color RGBA, non-interlaced
source-monarch.png:      PNG image data, 152 x 77, 8-bit/color RGBA, non-interlaced
source-monochrom.png:    PNG image data, 152 x 77, 8-bit/color RGBA, non-interlaced
source-mpd.png:          PNG image data, 270 x 85, 8-bit/color RGBA, non-interlaced
source-mychem.png:       PNG image data, 700 x 133, 8-bit/color RGBA, non-interlaced
source-mydrug.png:       PNG image data, 700 x 102, 8-bit/color RGBA, non-interlaced
source-mygene.png:       PNG image data, 128 x 128, 8-bit/color RGBA, interlaced
source-ncbi.png:         PNG image data, 32 x 32, 8-bit/color RGBA, non-interlaced
source-omia.png:         PNG image data, 87 x 24, 8-bit/color RGBA, non-interlaced
source-omim.png:         PNG image data, 384 x 142, 8-bit/color RGB, non-interlaced
source-orphanet.png:     PNG image data, 303 x 300, 8-bit/color RGBA, non-interlaced
source-panther.png:      PNG image data, 225 x 45, 8-bit/color RGB, non-interlaced
source-pharmgkb.png:     PNG image data, 30 x 30, 8-bit/color RGBA, non-interlaced
source-reactome.png:     PNG image data, 297 x 70, 8-bit/color RGBA, non-interlaced
source-rgd.png:          PNG image data, 150 x 111, 8-bit/color RGB, non-interlaced
source-sgd.png:          gzip compressed data, original size 9551
source-string.png:       PNG image data, 300 x 222, 8-bit/color RGBA, non-interlaced
source-ucscbands.png:    PNG image data, 145 x 55, 8-bit/color RGBA, non-interlaced
source-udp.png:          PNG image data, 200 x 47, 8-bit/color RGBA, non-interlaced
source-uniprot.ico:      MS Windows icon resource - 2 icons, 16x16, 32x32
source-vega.png:         PNG image data, 16 x 16, 8-bit/color RGBA, non-interlaced
source-wormbase.png:     PNG image data, 544 x 100, 16-bit/color RGBA, non-interlaced
source-zfin.png:         PNG image data, 115 x 36, 8-bit/color RGBA, non-interlaced
```

**Comment by monicacecilia** [comment]
They do to me. @kshefchek - if you have a moment, please have a look.

**Pull request merged**
