### PR TITLE
Publish via Jenkins to alpha.m.org. Add bundle analyze. Reduce bundle size. 

### PR DESCRIPTION
**Pull request by DoctorBud**
- Use / as default for publicPath, unless overridden by BUILD=nonrootdomain, which will use /monarch-ui/ for publicPath.
- Eliminate use of npx, which was overkill.
- Adds 'npm run analyze' for bundle analysis.
- Compiles GenomeFeatureView to reduce bundle size.
- Ensure that esprima.js is not included in bundle by using a NOP.js file.
- Fix image reference for Tomasz on Team page.
- Bump version to 0.0.2 (mostly to ensure that I can detect the version. Going to automate this versioning in the future).

### CODE REVIEW

**Comment by nathandunn** [comment]
I always feel a bit uncomfortable directly assessing anything in `node_modules/`.   I'm not sure the reason for NOT using npx?  I think referencing the vue client within the node_modules also feels awkward.

**Comment by nathandunn** [comment]
That bundle analyzer is crazy!  

Everything works that I tested.

**Comment by DoctorBud** [comment]
@nathandunn 
- `npx` by default will try to download a package unless you add the `--no-install` option, which makes the syntax cumbersome. I don't want it to download anything. When I first learned of `npx`, I thought it was a more proper way of accessing `node_modules/.bin`, so I adopted it. Now I'm unadopting it because got in my way when I was debugging my build config.
- Running the version of `vue-cli` that is installed via `package.json` is (I will argue) more correct than requiring the dev to have a globally installed version of vue-cli. It allows us to KNOW what version we are running, rather than having non-source-controlled version numbers in play.

**Comment by nathandunn** [comment]
@DoctorBud  I agree on both counts. 

In gradle / grails ecosystem (really the gold standard for everything), they usually provide a ./grailsw and ./gradlew locally that will download to the current project, once and only once, the package-specified version.    I think your approach is similar to this, but it feels like there should be a more boiled-in way.    This seems like it would be sufficient.

**Comment by kshefchek** [comment]
+1

**Pull request merged**
