### PR TITLE
removing charite, adding ada

### PR DESCRIPTION
**Pull request by iimpulse**
#297

### CODE REVIEW

**Comment by kshefchek** [comment]
I added a logo to the repo, but theres probably a better one that includes the name 'Ada' in the logo, @drseb or @monicacecilia do you have one?

**Comment by iimpulse** [comment]
@kshefchek did mine not get in? hmm

**Comment by drseb** [comment]
Hi, thanks for thinking of adding this. Please do not put this on the website for now. I have to check with our compliance department first. Thanks

**Comment by monicacecilia** [comment]
@iimpulse - please see @drseb's request to remove the Ada Health logo. We need to revert these changes. - And my apologies. I wasn't aware this wasn't appropriate. 

@drseb - what affiliation do you want to have on the page? Or please let us know if we should remove the affiliation altogether? Thanks!

**Comment by drseb** [comment]
Can I for now just have "monarch-initiative" as affiliation? If anybody wants to affiliate me with his university, let me know :-) 
I'll get back to you re:ada-logo. Thanks

**Comment by pnrobinson** [comment]
Hi Seb,
if you ever want to come stateside let me know! :-0

**Pull request merged**
